# Generated by Django 3.2.3 on 2021-05-16 11:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
