# Generated by Django 3.2.3 on 2021-05-16 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_questions_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='poll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.poll'),
        ),
    ]
