# Generated by Django 3.2.3 on 2021-05-21 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='country',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='movie',
            new_name='actor',
        ),
        migrations.RenameField(
            model_name='oscar',
            old_name='oscar_for_actor',
            new_name='actor',
        ),
        migrations.RenameField(
            model_name='oscar',
            old_name='oscar_for_movie',
            new_name='movie',
        ),
    ]
