# Generated by Django 3.2.3 on 2021-05-22 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20210521_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='movie',
        ),
        migrations.AddField(
            model_name='movie',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='movies.country'),
        ),
    ]
