# Generated by Django 3.2.3 on 2021-05-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'ordering': ['name', 'last_name', 'age']},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['title', 'genre', 'year']},
        ),
        migrations.RemoveField(
            model_name='movie',
            name='actor',
        ),
        migrations.AddField(
            model_name='movie',
            name='actor',
            field=models.ManyToManyField(blank=True, related_name='movies', to='movies.Actor'),
        ),
    ]
